// Article V2_MIBG — transcription fidèle de la version de référence validée par
// l'auteur (Dr B. F. P. Agboton), profil médecin nucléaire, gabarit en 26 sections.
// Concise, sourcée (citations numérotées → §25), domaine onco + cardio-neuro.
import { MIBG_UPTAKE, MIBG_BIODISTRIB, GAMMA_CAMERA, ALARA_TDS } from './diagrams.mjs';

const A = ['Dr Babatounde Fréjuste Pinocio Agboton', 'Assistance IA (Claude)'];

export const article = {
  id: 'V2_MIBG', cat: 'endocrinologie', catLabel: 'Endocrinologie',
  title: 'Scintigraphie à la MIBG (¹²³I/¹³¹I)',
  difficulty: 'avancé',
  tags: ['MIBG', 'iobenguane', '123I', '131I', 'phéochromocytome', 'paragangliome', 'neuroblastome', 'NET', 'innervation sympathique cardiaque', 'corps de Lewy', 'SIOPEN', 'théranostique'],
  targetAudience: ['patient', 'medecin_non_nuc', 'medecin_nuc'],
  authors: A, reviewStatus: 'ai_assisted',
  sources: [
    { title: '[1] Bombardieri E, Giammarile F, Aktolun C, et al. ¹³¹I/¹²³I-mIBG scintigraphy: procedure guidelines for tumour imaging. Eur J Nucl Med Mol Imaging 2010;37(12):2436-2446', url: 'https://doi.org/10.1007/s00259-010-1545-7' },
    { title: '[2] Taïeb D, Timmers HJ, Hindié E, et al. EANM 2012 guidelines for radionuclide imaging of phaeochromocytoma & paraganglioma. Eur J Nucl Med Mol Imaging 2012;39(12):1977-1995', url: 'https://www.eanm.org/publications/guidelines/' },
    { title: '[3] Taïeb D, Hicks RJ, Hindié E, et al. EANM/SNMMI Practice Guideline/Procedure Standard 2019 for radionuclide imaging of phaeochromocytoma & paraganglioma. Eur J Nucl Med Mol Imaging 2019;46(10):2112-2137', url: 'https://www.eanm.org/publications/guidelines/' },
    { title: '[4] Bar-Sever Z, Biassoni L, Shulkin B, et al. Guidelines on nuclear medicine imaging in neuroblastoma. Eur J Nucl Med Mol Imaging 2018;45(11):2009-2024', url: 'https://www.eanm.org/publications/guidelines/' },
    { title: '[5] SNMMI Procedure Standard for ¹³¹I/¹²³I-mIBG scintigraphy. SNMMI, 2010', url: 'https://www.snmmi.org/guidelines' },
    { title: '[6] ICRP Publication 128. Radiation Dose to Patients from Radiopharmaceuticals. Ann ICRP, 2015', url: 'https://www.icrp.org' },
    { title: '[7] Giammarile F, et al. Guide de réalisation de la scintigraphie à la MIBG. Médecine Nucléaire (SFMN)', url: 'https://www.sfmn.org' },
    { title: '[8] Solanki KK, et al. A pharmacological guide to medicines which interfere with the biodistribution of radiolabelled mIBG. Nucl Med Commun 1992 (+ tableau EANM des interférences)', url: 'https://pubmed.ncbi.nlm.nih.gov/' },
    { title: '[9] Jacobson AF, Senior R, Cerqueira MD, et al. (ADMIRE-HF). ¹²³I-mIBG imaging for prognosis in heart failure. J Am Coll Cardiol 2010;55(20):2212-2221', url: 'https://pubmed.ncbi.nlm.nih.gov/' },
    { title: '[10] McKeith IG, et al. Diagnosis and management of dementia with Lewy bodies — 4th consensus report. Neurology 2017;89(1):88-100', url: 'https://pubmed.ncbi.nlm.nih.gov/' },
    { title: '[11] Pryma DA, et al. Efficacy and safety of high-specific-activity ¹³¹I-MIBG (iobenguane I-131, Azedra) in metastatic/unresectable phaeochromocytoma-paraganglioma. 2018', url: 'https://pubmed.ncbi.nlm.nih.gov/' },
    { title: '[12] Timmers HJGM, et al. Superiority of ¹⁸F-FDG PET in metastatic SDHB-associated phaeochromocytoma/paraganglioma. J Clin Oncol 2007;25(16):2262-2269', url: 'https://pubmed.ncbi.nlm.nih.gov/' },
  ],
  content: {
    // §0 — Présentation générale (commune aux 4 profils)
    lead: 'La scintigraphie à la MIBG est un examen d’imagerie qui recherche dans tout le corps certaines tumeurs neuroendocrines — notamment le **phéochromocytome**, le **paragangliome** et le **neuroblastome** — ainsi que l’**innervation sympathique du cœur**. En une seule acquisition corps entier, elle les localise, évalue leur extension et détermine si un **traitement radioactif ciblé** (¹³¹I-MIBG) est envisageable.',
    patient: {
      sections: [
        { title: 'À quoi sert l’examen ?', text: 'À **localiser** certaines tumeurs rares (glandes surrénales, système nerveux) ou à évaluer le **fonctionnement nerveux du cœur**. Un traceur faiblement radioactif se fixe spécifiquement sur la cible, et une caméra réalise des images du corps entier — le plus souvent **le lendemain**.' },
        { title: 'Comment se préparer', list: [
          'Des **comprimés pour protéger la thyroïde** (iode/Lugol), à débuter la veille et à poursuivre quelques jours.',
          'Certains **médicaments** (tension, antidépresseurs, décongestionnants) sont arrêtés un temps **sur consigne médicale** — ne rien arrêter seul.',
          '**Pas de jeûne** nécessaire. Prévenez en cas de grossesse ou d’allaitement.',
        ] },
        { title: 'Le jour de l’examen', text: 'Une **injection lente** dans une veine. Les images sont prises le lendemain (± 2 jours), parfois complétées d’un examen couplé au scanner (TEMP/TDM). C’est indolore ; pensez à **bien boire**.' },
      ],
    },
    medecin_non_nuc: {
      sections: [
        { title: 'Indications — deux grands champs', list: [
          '**Oncologie (tumeurs neuroendocrines)** : phéochromocytome/paragangliome (localisation, multifocalité, métastases, **sélection avant ¹³¹I-MIBG**), **neuroblastome** de l’enfant (bilan, réponse, scores).',
          '**Cardio-neurologie (innervation sympathique)** : pronostic de l’**insuffisance cardiaque** (rapport cœur/médiastin H/M), et diagnostic différentiel des **maladies à corps de Lewy** vs parkinsonismes atypiques.',
        ] },
        { title: 'Avant d’adresser', infoBox: { type: 'warning', title: 'Deux points clés', text: '1) De nombreux **médicaments** (labétalol, tricycliques, sympathomimétiques, neuroleptiques) bloquent la captation → **faux négatifs** : à anticiper. 2) Pour le **phéo/para**, la **TEP au ⁶⁸Ga-DOTATATE** est souvent plus sensible (surtout têtes-et-cou et SDHB) ; la MIBG garde sa place pour le **neuroblastome**, le **cardiaque** et la **sélection théranostique**.' } },
        { title: 'Place dans la stratégie', text: 'Phéo/para : imagerie morphologique (TDM/IRM) puis imagerie fonctionnelle **guidée par le génotype** (DOTATATE souvent privilégié ; MIBG si projet de traitement ¹³¹I-MIBG). Neuroblastome : la MIBG est l’**examen pivot**. Cardiaque : stratification pronostique et aide au diagnostic des syndromes parkinsoniens.' },
      ],
    },
    medecin_nuc: {
      sections: [
        // ───────── MOUVEMENT A — COMPRENDRE ─────────
        { title: 'A1 · Carte d’identité', text: '| Champ | Valeur |\n|---|---|\n| **Traceur principal** | **¹²³I-MIBG** (iobenguane I-123) ; alternative **¹³¹I-MIBG** (¹²⁴I-MIBG TEP émergent) |\n| **Émission × énergie** | ¹²³I : γ **159 keV** · ¹³¹I : **364 keV** + β⁻ |\n| **Période physique** | ¹²³I : **13,2 h** · ¹³¹I : **8,0 j** |\n| **Voie × activité adulte** | **IV lente** (≤ 5 min) · ¹²³I ≈ **370 MBq** [protocole local] |\n| **Pédiatrie** | ¹²³I-MIBG **80–400 MBq** (carte de dose EANM) |\n| **Délai injection→images** | ¹²³I : **24 h** (± 48 h) · ¹³¹I : 24–72 h |\n| **Durée d’acquisition** | Corps entier **30–45 min** (+ TEMP/TDM) |\n| **Cible biologique** | Transporteur de la noradrénaline (**NET / uptake-1**) |\n| **Dose efficace adulte** | ¹²³I ≈ **0,013 mSv/MBq** · ¹³¹I ≈ **0,14 mSv/MBq** |\n| **Préparation clé** | **Blocage thyroïdien** + arrêt des médicaments interférents |\n| **Élimination** | Urinaire · **pas de jeûne requis** |\n| **Indications phares** | Phéo · paragangliome · neuroblastome (bilan + sélection théranostique) · **innervation sympathique cardiaque** |\n\nLes activités exactes et le détail du blocage thyroïdien sont à adapter au protocole de chaque service.',
          stats: [{ value: '159 keV', label: 'γ du ¹²³I (caméra idéale)' }, { value: '370 MBq', label: 'Activité adulte ¹²³I-MIBG' }, { value: '24 h', label: 'Délai standard d’imagerie' }, { value: '≈ 5 mSv', label: 'Dose efficace (¹²³I, adulte)' }] },
        { title: 'A2 · Définition', text: 'La **méta-iodobenzylguanidine (MIBG)**, ou iobenguane, est un **analogue de la noradrénaline** : une molécule de synthèse dérivée de la guanéthidine, qui se comporte comme un « faux neurotransmetteur ». Marquée par un isotope radioactif de l’iode (**¹²³I** à visée diagnostique, **¹³¹I** à visée surtout thérapeutique), elle réalise une **imagerie fonctionnelle et moléculaire** du système nerveux sympathique et des tumeurs qui en dérivent.[1,2]\n\nContrairement à la TDM ou à l’IRM, qui montrent la morphologie, la scintigraphie MIBG révèle une **propriété biologique** : la capacité d’une cellule à capter et stocker la noradrénaline. Elle apporte donc une information de **caractérisation** (le tissu est-il d’origine sympatho-adrénergique ?) et de **cartographie corps entier** (où sont toutes les localisations ?). C’est aussi un examen **théranostique** : un examen positif au ¹²³I-MIBG identifie les patients candidats à un traitement par **¹³¹I-MIBG**.[2,3]' },
        { title: 'A3 · Rappels anatomiques & physiologiques', text: 'Le système nerveux sympathique régule les fonctions involontaires (cœur, vaisseaux, viscères). Ses neurones post-ganglionnaires libèrent la **noradrénaline**, recaptée dans la terminaison par un transporteur membranaire spécifique. La **médullosurrénale** est un ganglion sympathique modifié : ses **cellules chromaffines** synthétisent et stockent les catécholamines dans des granules de sécrétion.\n\nLes tumeurs explorées dérivent toutes de la **crête neurale** : le **phéochromocytome** (médullosurrénale), le **paragangliome** (paraganglions extra-surrénaliens, du crâne au pelvis) et le **neuroblastome** (tumeur sympathique de l’enfant). Toutes partagent la caractéristique exploitée par la MIBG : l’expression du **transporteur de la noradrénaline** et la présence de **granules de stockage**.[1,4]' },
        { title: 'A4 · Principe : la cible biologique', text: '**Pourquoi ça marche.** La MIBG emprunte la même voie que la noradrénaline : captée activement par le **NET (uptake-1)** — mécanisme spécifique, énergie- et sodium-dépendant — puis stockée dans les granules via le **VMAT**. Surtout, elle **n’est pas métabolisée** (ni MAO ni COMT) : elle est retenue durablement, ce qui permet l’imagerie à 24 h.[1]\n\nLa cible est donc le **tissu exprimant le NET et capable de stockage** : tissu sympatho-adrénergique normal et tumeurs neuroendocrines de la crête neurale.\n\n- **Hyperfixation** = densité élevée de NET et de granules (tumeur active).\n- **Hypofixation / absence** = perte d’expression du NET (tumeur dédifférenciée, mutation **SDHB**), nécrose, ou **blocage pharmacologique** du transporteur.',
          figure: { svg: MIBG_UPTAKE, alt: 'Synapse noradrénergique et cellule chromaffine : recapture par le NET (uptake-1) puis stockage vésiculaire (VMAT) — la voie détournée par la MIBG.', caption: 'Fig. 1 — Recapture par le NET (uptake-1) puis stockage vésiculaire : la voie détournée par la MIBG.' },
          infoBox: { type: 'info', title: 'Point expert', text: 'La cible est **indépendante du radio-isotope** : ¹²³I et ¹³¹I ciblent exactement le même transporteur. Le choix de l’isotope ne change que la qualité d’image et la dosimétrie, jamais le ciblage (cf. §B7). C’est ce qui fonde la **paire théranostique** : on visualise avec un isotope et on traite avec l’autre.' } },
        { title: 'A5 · Indications', text: 'Deux grands champs ; pour chaque indication, le rationale renvoie au §A4 (la MIBG n’est positive que si la cible NET + stockage est exprimée).\n\n**▸ Oncologie — tumeurs neuroendocrines**\n\n- **Phéochromocytome & paragangliome** : localisation et extension d’une tumeur biochimiquement prouvée mais non localisée, multifocalité, métastases, **sélection pré-thérapeutique ¹³¹I-MIBG**, suivi. Sensibilité **élevée pour le phéo surrénalien**, mais **faible pour les paragangliomes tête-et-cou et les formes SDHB**, où la TEP (Ga-DOTATATE, ¹⁸F-FDG) est supérieure.[2,3]\n- **Neuroblastome** : examen **central en pédiatrie** (bilan d’extension, évaluation de la réponse, rechutes). ~**90 %** des neuroblastomes fixent la MIBG ; extension cotée par les scores **Curie / SIOPEN**.[4]\n- **Autres TNE** (carcinoïde, carcinome médullaire thyroïdien, tumeur de Merkel) : captation inconstante, sensibilité faible → ⁶⁸Ga-DOTATATE généralement préféré.[1]\n\n**▸ Cardio-neurologie — innervation sympathique**\n\n- **Insuffisance cardiaque** : le **rapport cœur/médiastin (H/M)** et le **washout** (images planaires précoces ~15 min et tardives 3–4 h) reflètent l’intégrité de l’innervation sympathique du myocarde. Un **H/M abaissé** est un facteur **pronostique** (événements cardiaques, mortalité) — étude **ADMIRE-HF**.[9]\n- **Maladies à corps de Lewy** : la dénervation sympathique cardiaque est précoce (Parkinson, **démence à corps de Lewy**, atrophie autonome). Un **H/M tardif ≤ 2,2** distingue ces affections des parkinsonismes atypiques (AMS, PSP) et d’Alzheimer ; pour la DCL, Se ~**98 %**, Sp ~**94 %** — biomarqueur indicatif des critères diagnostiques.[10]' },
        { title: 'A6 · Contre-indications & précautions', text: 'Il n’existe **pas de contre-indication absolue** à la scintigraphie diagnostique. Les points de vigilance sont relatifs et relèvent surtout de la préparation et de la radioprotection.\n\n| Situation | Type | Conduite |\n|---|---|---|\n| **Grossesse** | Relative | Évaluer bénéfice/risque ; reporter si possible ; jamais en routine.[2] |\n| **Allaitement** | Relative | Interrompre ≥ 48 h après ¹²³I-MIBG ; **arrêt complet** si ¹³¹I-MIBG.[2] |\n| **Blocage thyroïdien insuffisant** | À corriger | Fixation thyroïdienne de l’iode libre → image dégradée + irradiation (cf. §B8). |\n| **Médicaments interférents** | À gérer | Faux négatifs → arrêt programmé avant l’examen (cf. §B8). |\n| **Insuffisance rénale sévère** | Relative | Élimination ralentie ; pertinence surtout pour le volet ¹³¹I-MIBG thérapeutique. |',
          infoBox: { type: 'warning', title: 'Précaution', text: 'Grossesse et allaitement doivent être **systématiquement recherchés** avant l’injection. L’allaitement est interrompu **au minimum 48 h** après un examen au ¹²³I-MIBG, et **définitivement** en cas d’emploi du ¹³¹I-MIBG.' } },

        // ───────── MOUVEMENT B — RÉALISER ─────────
        { title: 'B7 · Radiopharmaceutique(s) & mécanisme de fixation', text: '**(a) Mécanisme moléculaire.** La MIBG associe le squelette **benzylguanidine** (dérivé de la guanéthidine) à un atome d’iode radioactif. Elle pénètre la cellule par deux voies : **uptake-1** (NET, actif et spécifique, prédominant aux faibles concentrations diagnostiques) et **uptake-2** (diffusion passive non spécifique, significative seulement aux fortes concentrations thérapeutiques). Une fois intracellulaire, elle est stockée dans les granules (VMAT) et **non métabolisée**.[1] Le choix de l’isotope ne modifie pas le ciblage, mais détermine la qualité d’image et la dose.\n\n| Caractéristique | ¹²³I-MIBG (diagnostic) | ¹³¹I-MIBG |\n|---|---|---|\n| Émission × énergie | γ pur **159 keV** | **364 keV** + β⁻ (thérapeutique) |\n| Période physique | 13,2 h | 8,0 jours |\n| Qualité d’image | Élevée (adaptée aux γ-caméras) | Médiocre (haute énergie) |\n| TEMP / TEMP-TDM | Aisée, recommandée | Difficile |\n| Délai d’imagerie | 24 h (± 48 h) | 24–72 h |\n| Dose efficace adulte | 0,013 mSv/MBq | 0,14 mSv/MBq |\n| Usage principal | **Diagnostic (référence)** | Surtout thérapie ; diagnostic non recommandé |\n\n**(b) Production & marquage.** ¹²³I produit par **cyclotron** (coût élevé, disponibilité variable) ; ¹³¹I produit en réacteur. La forme à **haute activité spécifique** (sans entraîneur) est désormais standard pour la thérapie (Azedra®).[11]\n\n**(c) Contrôle qualité du traceur** : pureté radiochimique (l’**iode libre** se fixe sur thyroïde/estomac/salivaires et dégrade l’image, cf. §C14), pureté radionucléidique, pH, stérilité/apyrogénicité, activité vérifiée à l’activimètre.\n\n**(d) Activités & voie** : **IV lente (≤ 5 min)** pour éviter une réaction hypertensive catécholaminergique. Adulte : ¹²³I-MIBG ≈ 370 MBq [à adapter] ; enfant : carte de dose pédiatrique EANM (¹²³I-MIBG **80–400 MBq**).[2,14]',
          infoBox: { type: 'info', title: 'Point expert', text: 'Le ¹²³I est préféré au ¹³¹I en imagerie pour **quatre raisons** : meilleure détection du photon de 159 keV, charge dosimétrique plus faible (donc activité plus élevée et meilleur comptage), faisabilité de la **TEMP**, et délai injection-imagerie plus court (24 h vs 48–72 h).[2] Le **¹²⁴I-MIBG** (émetteur de positons) émerge pour la TEP et la dosimétrie prédictive avant traitement.' } },
        { title: 'B8 · Préparation du patient', text: 'La préparation conditionne la validité de l’examen. Deux éléments sont spécifiques : le **blocage thyroïdien** et l’**arrêt des médicaments interférents**. **Pas de jeûne requis.**\n\n**Blocage thyroïdien.** Pour empêcher la fixation de l’iode libre par la thyroïde : **iodure de potassium (KI)**, solution de Lugol ou perchlorate de potassium, débuté **la veille** et poursuivi **5–7 jours** (durée prolongée pour le ¹³¹I). Posologie usuelle KI : **100 mg/j adulte, 2 mg/kg enfant** ; prévient l’entrée de **> 95 %** de l’iode radioactif.[1,5]\n\n**Médicaments interférents — à arrêter** (bloquent l’uptake-1 ou déplètent les granules → faux négatifs ; délais variables, souvent 24–72 h, jusqu’à plusieurs semaines) :[1,8]\n\n| Classe | Exemples | Arrêt avant l’examen |\n|---|---|---|\n| Antidépresseurs tricycliques | Amitriptyline, imipramine… | 48–72 h |\n| Sympathomimétiques | Pseudoéphédrine, phényléphrine, amphétamines, cocaïne | 48–72 h |\n| Antihypertenseurs / cardiovasc. | **Labétalol**, réserpine, certains inhibiteurs calciques | 48–72 h |\n| Neuroleptiques | Halopéridol, flupentixol, fluphénazine, rispéridone | 24 h à 1 mois |\n| Autres | Tramadol, certains opioïdes | 48 h |',
          steps: [
            { title: 'Avant J', text: 'Vérifier indication, grossesse/allaitement, fonction rénale ; planifier l’arrêt des interférents ; débuter le blocage thyroïdien la veille.' },
            { title: 'Le jour J', text: 'Confirmer le blocage ; injection IV lente (≤ 5 min) ; hydratation ; vidange vésicale avant l’imagerie pelvienne ; sédation éventuelle chez le jeune enfant ; information/consentement.' },
          ],
          infoBox: { type: 'warning', title: 'Précaution', text: 'Beaucoup de **bêta-bloquants sont compatibles**, mais le **labétalol** (alpha-bêta) doit être arrêté. Toujours vérifier le traitement complet. Certaines équipes recommandent aussi d’éviter, la veille, les aliments riches en catécholamines/vanilline (chocolat, fromages bleus).[8]' } },
        { title: 'B9 · Instrument, CQ & protocole d’acquisition', text: '**(a) CQ de l’instrument — prérequis.** Uniformité (quotidienne), pic d’énergie (peaking sur 159 keV), résolution spatiale et linéarité, sensibilité ; pour la TEMP : centre de rotation (COR) et uniformité tomographique.\n\n**(b) Acquisition (tumeurs).** Fenêtre centrée sur **159 keV (± 10 %)**. Images planaires corps entier antérieures/postérieures + statiques (tête-cou avec obliques, thorax, abdomen, pelvis) de 10–15 min. Imagerie à **24 h** (± 48 h ; ¹³¹I : 24–72 h). Une **TEMP/TDM** des régions d’intérêt augmente nettement la sensibilité et la localisation.[1,3]\n\n**(c) TDM associée** : basse dose pour correction d’atténuation et repérage ; diagnostique selon les cas.\n\n**(d) Protocole cardiaque.** Images planaires thoraciques antérieures **précoces (15 min)** et **tardives (3–4 h)** ; mesure du **H/M** et du **washout**. La standardisation **MEGP** des indices est importante (le H/M dépend du collimateur et de la caméra).[9,10]\n\n**(e) Pédiatrie** : activités selon la carte EANM ; sédation/immobilisation possibles.[14]',
          figure: { svg: GAMMA_CAMERA, alt: 'Schéma d’une gamma-caméra : collimateur, cristal NaI(Tl), photomultiplicateurs, électronique de positionnement.', caption: 'Fig. 2 — γ-caméra (planaire + TEMP/TDM) ; le collimateur est adapté à l’énergie de l’iode.' },
          infoBox: { type: 'warning', title: 'Piège — choix du collimateur (¹²³I)', text: 'Le ¹²³I émet aussi des **photons de haute énergie (≈ 529 keV)** responsables de pénétration septale et d’un **artefact en étoile** avec un collimateur basse énergie. Un collimateur **moyenne énergie (MEGP)** est souvent préféré ; un LEHR reste utilisable. Pour le ¹³¹I, un collimateur **haute énergie est obligatoire**.[5]' } },
        { title: 'B10 · Traitement, reconstruction & quantification', text: 'Reconstruction TEMP par algorithme **itératif (OSEM)**, avec **correction d’atténuation** (TDM) et de diffusé, fusion TEMP-TDM.\n\n**Quantification — neuroblastome.** L’étendue est cotée par des **scores semi-quantitatifs** standardisés, indispensables au suivi :\n- **Score de Curie** : squelette divisé en secteurs + 1 secteur tissus mous ; chaque segment reçoit une note d’intensité ; somme = score global.\n- **Score SIOPEN** : **12 segments** corporels, cotés **0–6** chacun selon le nombre de lésions ; échelle validée par un panel international (SIOPEN-R-NET).[4]\n\n**Quantification — cardiaque.** Le **H/M** se calcule en plaçant une ROI sur le cœur (H) et le médiastin supérieur (M) sur l’image planaire antérieure, précoce et tardive. Le **washout** mesure la perte d’activité entre images précoce et tardive (corrigée de la décroissance et du fond). Ces indices doivent être **standardisés (MEGP)** pour être comparables entre centres.[9,10]' },

        // ───────── MOUVEMENT C — INTERPRÉTER ─────────
        { title: 'C11 · Aspect normal & variantes physiologiques', text: 'Reconnaître la **biodistribution normale** est le préalable à toute interprétation. Le ¹²³I-MIBG se fixe physiologiquement sur :\n\n- **Glandes salivaires** et muqueuse nasopharyngée ;\n- **Myocarde** (innervation sympathique) ;\n- **Foie** (intense), **rate**, poumons (surtout en phase précoce) ;\n- **Tube digestif** (excrétion) et **voies urinaires/vessie** (élimination) ;\n- **Médullosurrénale** : fixation faible et symétrique, mieux visible avec le ¹³¹I aux temps tardifs ;\n- **Graisse brune** (sujet jeune, froid) et, en cas de blocage incomplet, **thyroïde**.',
          figure: { svg: MIBG_BIODISTRIB, alt: 'Biodistribution normale du ¹²³I-MIBG (corps entier, 24 h) : glandes salivaires, myocarde, foie, rate, intestin et vessie.', caption: 'Fig. 3 — Biodistribution normale (24 h) : l’image de référence à garder en repère.' },
          infoBox: { type: 'info', title: 'Point expert', text: 'Une fixation surrénalienne **faible et symétrique** est physiologique. La difficulté est de la distinguer d’une **hyperplasie médullosurrénalienne** (contextes SDHx, NEM2) ou d’un **petit phéochromocytome** — d’où l’intérêt de la **TEMP-TDM** et de l’**asymétrie**.' } },
        { title: 'C12 · Sémiologie & interprétation', text: '**Méthode de lecture systématique** : (1) vérifier la qualité technique et le blocage thyroïdien ; (2) parcourir la biodistribution physiologique ; (3) repérer toute **fixation anormale** (focale, asymétrique, extra-physiologique) ; (4) corréler à la **TEMP-TDM** ; (5) **coter** si indiqué (Curie/SIOPEN pour le neuroblastome, H/M pour le cardiaque) ; (6) conclure en répondant à la question clinique.\n\n**Patterns pathologiques.** Une fixation **focale intense extra-physiologique** signe une tumeur avide : masse surrénalienne (phéo) ou extra-surrénalienne (paragangliome), atteintes métastatiques (os, ganglions, foie). Dans le neuroblastome, l’atteinte médullaire diffuse et les métastases osseuses sont cotées par les scores.\n\n**Cardiaque / neurologique.** Une **réduction du H/M** et une **augmentation du washout** traduisent une dénervation sympathique : pronostic défavorable dans l’insuffisance cardiaque, et — au **seuil tardif ≤ 2,2** — argument fort en faveur d’une **maladie à corps de Lewy** contre un parkinsonisme atypique ou une maladie d’Alzheimer.[9,10]\n\nConclure en **positif / négatif / équivoque**, en intégrant systématiquement la TEMP-TDM et le contexte biochimique/génétique.' },
        { title: 'C13 · Compte rendu structuré', text: 'Trame recommandée :\n1. **Technique** : traceur et activité, blocage thyroïdien, médicaments interférents arrêtés, délais, planaire/TEMP-TDM, collimateur.\n2. **Biodistribution physiologique** : conforme ou non.\n3. **Anomalies** : localisation, intensité, corrélation TEMP-TDM, caractère uni/multifocal, métastases.\n4. **Cotation** : score de Curie/SIOPEN (neuroblastome) ou H/M + washout (cardiaque), le cas échéant.\n5. **Conclusion** : réponse explicite à la question clinique (localisation ? extension ? avidité MIBG en vue d’un traitement ¹³¹I-MIBG ?).',
          infoBox: { type: 'info', title: 'Point expert', text: 'Pour un neuroblastome, **toujours fournir le score chiffré** (Curie/SIOPEN) : c’est lui qui permettra la comparaison au fil du traitement. Pour une indication théranostique, **conclure explicitement sur l’avidité MIBG** de l’ensemble des lésions.' } },
        { title: 'C14 · Pièges, artefacts & faux positifs/négatifs', text: 'Pour chaque piège : identifier la cause, reconnaître l’aspect, et corriger (TEMP-TDM, clichés tardifs, contrôle de la préparation).',
          infoBox: { type: 'warning', title: 'Piège — faux négatifs / faux positifs / iode libre', text: '**Faux négatifs** : petites lésions (sous la résolution), tumeurs dédifférenciées/nécrotiques, **médicaments interférents non arrêtés**, formes peu avides (paragangliomes tête-cou, **SDHB**), vessie non vidée masquant le pelvis.[5] · **Faux positifs** : fixation surrénalienne physiologique (parfois majorée par la correction d’atténuation TDM), graisse brune, activité digestive/contamination urinaire, autres tumeurs NET (carcinoïde, CMT, Merkel, ganglioneurome).[3] · **Iode libre** (pureté insuffisante) : fixation thyroïdienne, gastrique et salivaire anormale → vérifier le CQ du traceur et le blocage (§B7, §B8).' } },

        // ───────── MOUVEMENT D — MAÎTRISER & SITUER ─────────
        { title: 'D15 · Dosimétrie', text: 'Données de référence (CIPR 128 / EANM).[2,6]\n\n| Traceur | Adulte (mSv/MBq) | Enfant 5 ans (mSv/MBq) |\n|---|---|---|\n| ¹²³I-MIBG | **0,013** | 0,037 |\n| ¹³¹I-MIBG | **0,14** | 0,43 |\n\nÀ **370 MBq** de ¹²³I-MIBG, la dose efficace adulte est de l’ordre de **5 mSv** [à confirmer selon l’activité retenue]. Organes les plus exposés : foie, paroi vésicale, glandes salivaires, cœur. La TEMP-TDM ajoute la dose du scanner (CTDIvol typiquement 3–5 mGy).[2]\n\n- **Pédiatrie** : dose par MBq plus élevée → activités adaptées (carte EANM), hydratation/vidange vésicale.\n- **Grossesse/allaitement** : évaluation bénéfice/risque ; interruption de l’allaitement ≥ 48 h (¹²³I), arrêt complet (¹³¹I).\n- Distinguer **dose absorbée** (Gy, par organe) et **dose efficace** (mSv, corps entier pondéré).\n- **Théranostique** : le ¹²⁴I-MIBG TEP permet une **dosimétrie prédictive** avant traitement par ¹³¹I-MIBG.' },
        { title: 'D16 · Radioprotection', text: 'Principes : **justification, optimisation (ALARA), limitation**. La radioprotection se pense **par cible** :\n\n| Cible | Mesures clés |\n|---|---|\n| **Personnel** | Blindage de seringue, distance, temps, dosimétrie passive et opérationnelle, zonage ; vigilance accrue avec le ¹³¹I (haute énergie + β⁻). |\n| **Entourage / public** | Patient « source » : consignes post-examen (hydratation, mictions fréquentes, distance vis-à-vis des enfants et femmes enceintes pendant la période utile). |\n| **Patient** | Justification, optimisation de l’activité, blocage thyroïdien. |\n\n**Effluents et déchets radioactifs** : gestion et décroissance (8 j pour le ¹³¹I impose un stockage prolongé). Traçabilité et conduite en cas de contamination selon la procédure du service.[5]',
          figure: { svg: ALARA_TDS, alt: 'Temps, distance, écran : les trois leviers de réduction de dose (ALARA).', caption: 'Fig. 4 — Temps / distance / écran : structure les consignes au personnel et à l’entourage.' } },
        { title: 'D17 · Performances diagnostiques & comparaison', text: 'La sensibilité dépend fortement de l’indication et du génotype. Globalement, la MIBG a été **dépassée par la TEP** pour le phéo/para, mais conserve sa place pour le neuroblastome et la sélection théranostique.\n\n| Modalité | Sensibilité (phéo/para) | Atouts / limites |\n|---|---|---|\n| ¹²³I/¹³¹I-MIBG | **38 %** (méta-analyse, toutes formes) | Faible pour HNPGL et SDHB ; **indispensable pour la sélection ¹³¹I-MIBG**.[18] |\n| ⁶⁸Ga-DOTATATE TEP | **93 %** | Supérieure, surtout HNPGL/SDHx ; 1ʳᵉ intention fonctionnelle souvent retenue. |\n| ¹⁸F-FDOPA TEP | **80 %** | Excellente pour phéo/para et neuroblastome. |\n| ¹⁸F-FDG TEP | **74 %** | Meilleure dans les formes SDHB et dédifférenciées. |\n| TDM / IRM | Élevée (détection) | Anatomique, peu spécifique. |\n\nNeuroblastome : la MIBG reste centrale (~90 % avides), le ¹⁸F-FDG servant si tumeur MIBG-négative.[4] Pour les **HNPGL**, sensibilité MIBG faible (**10–42 %**) vs Ga-DOTATATE ~100 %.[12]' },
        { title: 'D18 · Place dans la stratégie & algorithmes décisionnels', text: '**Phéochromocytome / paragangliome.** Après confirmation biochimique et imagerie anatomique (TDM/IRM), l’imagerie fonctionnelle est **guidée par le génotype** : ⁶⁸Ga-DOTATATE souvent privilégié (surtout HNPGL/SDHx), ¹⁸F-FDG pour les formes SDHB/dédifférenciées. La **MIBG** est demandée spécifiquement pour **évaluer l’avidité en vue d’un traitement ¹³¹I-MIBG** (logique théranostique).[3]\n\n**Neuroblastome.** La MIBG est l’**examen pivot** du bilan d’extension, de l’évaluation de réponse (Curie/SIOPEN) et du suivi ; la TEP (FDG, DOPA, DOTA) complète selon les cas.[4]\n\n**Cardio-neurologie.** Stratification pronostique de l’insuffisance cardiaque ; aide au diagnostic différentiel des syndromes parkinsoniens (corps de Lewy vs atypiques).[9,10]\n\n*Arbre décisionnel (phéo/para)* : suspicion → biochimie → TDM/IRM → imagerie fonctionnelle selon génotype (DOTATATE / FDG) → **MIBG si projet thérapeutique ¹³¹I-MIBG**.' },
        { title: 'D19 · Examens apparentés & variantes', text: '| Examen apparenté | Cible / différence | Quand le préférer |\n|---|---|---|\n| **¹³¹I-MIBG thérapeutique** | Même vecteur, visée β⁻ | Tumeur MIBG-avide non résécable (paire théranostique). |\n| **¹²⁴I-MIBG TEP** | TEP + dosimétrie prédictive | Quantification et planification avant ¹³¹I-MIBG. |\n| **⁶⁸Ga-DOTATATE TEP** | Récepteurs de la somatostatine | Phéo/para (surtout HNPGL/SDHx), bilan TNE. |\n| **¹⁸F-FDOPA / ¹⁸F-FDG TEP** | Métabolisme DOPA / glucose | FDOPA : haute Se ; FDG : formes SDHB/dédifférenciées. |\n| **¹²³I-FP-CIT (DaTscan)** | Transporteur dopaminergique cérébral | Parkinsonisme : complément cérébral du MIBG cardiaque. |\n| **¹⁷⁷Lu-DOTATATE** | Théranostic récepteurs somatostatine | Alternative au ¹³¹I-MIBG selon l’expression réceptorielle. |' },

        // ───────── MOUVEMENT E — ANCRER & ÉVALUER ─────────
        { title: 'E20 · Cas cliniques commentés', steps: [
          { title: 'Cas 1 — Phéochromocytome métastatique (sélection théranostique)', text: '*Contexte* : femme de 40 ans, HTA paroxystique, métanéphrines élevées ; TDM : masse surrénalienne droite + nodules osseux. *Images* : ¹²³I-MIBG corps entier + TEMP-TDM : fixation intense surrénalienne droite et de plusieurs lésions osseuses. *Analyse* : toutes les lésions sont MIBG-avides → maladie accessible à un traitement ¹³¹I-MIBG. *Conclusion* : phéochromocytome malin **MIBG-avide ; candidat au ¹³¹I-MIBG**.' },
          { title: 'Cas 2 — Neuroblastome (bilan d’extension et score)', text: '*Contexte* : enfant de 3 ans, masse abdominale, catécholamines urinaires élevées. *Images* : ¹²³I-MIBG : fixation de la masse primitive et de multiples foyers médullaires osseux. *Analyse* : atteinte métastatique étendue → cotation **Curie/SIOPEN** servant de référence pour la réponse. *Conclusion* : neuroblastome métastatique MIBG-avide ; **score initial documenté** pour le suivi.' },
          { title: 'Cas 3 — Suspicion de maladie à corps de Lewy', text: '*Contexte* : homme de 68 ans, syndrome parkinsonien + troubles cognitifs fluctuants. *Images* : ¹²³I-MIBG **cardiaque** planaire (15 min et 4 h) : **H/M abaissé**, washout accéléré. *Analyse* : dénervation sympathique cardiaque ; au seuil tardif ≤ 2,2 → argument fort pour une **maladie à corps de Lewy**. *Conclusion* : profil compatible avec une DCL plutôt qu’un parkinsonisme atypique.' },
        ] },
        { title: 'E21 · Points clés / à retenir', list: [
          'MIBG = **analogue de la noradrénaline**, capté par le **NET (uptake-1)**, stocké et **non métabolisé** → imagerie sympatho-adrénergique et des tumeurs de la crête neurale.',
          '**¹²³I-MIBG = diagnostic** (159 keV, 13,2 h, TEMP possible) ; **¹³¹I-MIBG = thérapie** (364 keV + β⁻) → **paire théranostique**.',
          'Préparation : **blocage thyroïdien** (KI/Lugol, dès la veille, 5–7 j) + **arrêt des médicaments interférents** (tricycliques, sympathomimétiques, labétalol, neuroleptiques) ; **pas de jeûne**.',
          'Collimateur : **moyenne énergie** souvent préféré pour le ¹²³I (pénétration septale à 529 keV) ; **haute énergie** pour le ¹³¹I.',
          'Indications : phéo/para, **neuroblastome** (scores Curie/SIOPEN), **innervation cardiaque** (H/M, washout — insuffisance cardiaque, corps de Lewy, seuil ≤ 2,2).',
          'Performance : la **TEP (Ga-DOTATATE) dépasse la MIBG** pour phéo/para (surtout HNPGL/SDHB) ; la MIBG reste centrale pour le **neuroblastome** et la **sélection ¹³¹I-MIBG**.',
          'Dose efficace : ¹²³I-MIBG ≈ **0,013 mSv/MBq** (adulte).',
          'Pièges : fixation surrénalienne physiologique, graisse brune, **iode libre** (thyroïde/estomac), **faux négatifs** si médicaments non arrêtés.',
        ] },
        { title: 'E22 · FAQ & pièges d’examen', text: '**Pourquoi bloquer la thyroïde ?** Le radiopharmaceutique contient toujours un peu d’**iode libre** qui se fixerait sur la thyroïde (irradiation + artefact).\n\n**Uptake-1 vs uptake-2 ?** L’uptake-1 (NET, actif, spécifique) prédomine aux doses diagnostiques ; l’uptake-2 (diffusion passive) ne compte qu’aux fortes doses thérapeutiques.\n\n**Pourquoi préférer le ¹²³I au ¹³¹I en imagerie ?** Meilleure qualité d’image (159 keV), dose plus faible, **TEMP faisable**, délai plus court (24 h).\n\n**MIBG ou Ga-DOTATATE ?** Le DOTATATE est **plus sensible** pour phéo/para (surtout tête-et-cou, SDHB) ; la MIBG garde sa place pour décider d’un traitement ¹³¹I-MIBG et pour le neuroblastome.\n\n**Quel seuil de H/M pour les corps de Lewy ?** Un seuil tardif souvent retenu est **≤ 2,2**, mais il dépend du matériel (standardisation MEGP indispensable).\n\n**Quels médicaments arrêter en priorité ?** Tricycliques, sympathomimétiques, **labétalol**, réserpine, neuroleptiques.\n\n*(Quiz interactif §23 et fiche de révision téléchargeable §24 : fonctionnalités de la plateforme à activer.)*' },
        { title: 'E25 · Références & liens', text: 'Références complètes et datées en bas de page (**Sources & Références**) : Bombardieri EANM 2010 [1], Taïeb EANM 2012 [2] et EANM/SNMMI 2019 [3], Bar-Sever neuroblastome 2018 [4], SNMMI 2010 [5], ICRP 128 [6], Giammarile SFMN [7], Solanki interférences 1992 [8], Jacobson ADMIRE-HF 2010 [9], McKeith DCL 2017 [10], Pryma Azedra 2018 [11], Timmers SDHB-FDG 2007 [12].\n\n**Carte de liens (réseau de l’article)** — Traceurs : ¹²³I-MIBG, ¹³¹I-MIBG · Maladies : phéochromocytome, paragangliome, neuroblastome, **corps de Lewy / insuffisance cardiaque** · Examens : ⁶⁸Ga-DOTATATE, ¹⁸F-FDOPA, ¹⁸F-FDG, DaTscan · Théranostique : ¹³¹I-MIBG, ¹⁷⁷Lu-DOTATATE. *Dernière mise à jour : juin 2026 — version de travail (profil médecin nucléaire).*' },
      ],
    },
  },
};
